### ISSUE TITLE
Missing `exp_dir` and `args.pkl` file for loading pretrained SSAMBA model

### ISSUE THREAD

**Issue by MorenoLaQuatra** [SiavashShams/ssamba#6]
Hi,

First of all, thank you for this repository and your contributions to the field!

I am trying to load a pretrained SSAMBA model and I noticed that the code relies on an `args.pkl` file, which is supposed to be located in `exp_dir`. However, it's unclear where exactly this `exp_dir` is located when working with pretrained models.

Can we use the default parameters available [here](https://github.com/SiavashShams/ssamba/blob/main/src/run_amba.py)?

My questions would be:

1. Where should the `exp_dir` be located when using the pretrained models provided?
2. If it’s not available, could you provide access to the `args.pkl` file for these models, or guide me on how to reconstruct it?

Thanks for your help!

**Comment by SiavashShams** [comment]
Hi Moreno,

Thanks for reaching out, and we appreciate your interest in SSAMBA!

The primary function of `args.pkl` is to store the configuration parameters used during pretraining, but when it comes to loading the model weights and running inference, the `.pth` file is usually sufficient.

You can load the pre-trained model like this:

```python
import torch

sd = torch.load("/path/to/ssast_base_300.pth", map_location=device)
```

This will load the state dictionary (model weights) without needing the `args.pkl` file. However, if you're running into specific issues or need certain hyperparameters from the training process (like dataset mean, standard deviation, etc.), those might have been stored in `args.pkl`. Some of these parameters are set to the default in the file you referred to. Some of them are overridden by [this](https://github.com/SiavashShams/ssamba/blob/019b276c2cde80bb5d58f51e589eb5b441a73ead/src/pretrain/run_mask_patch.sh).

Please let us know if this helped solve your problem, if not, we can provide you with the args.pkl file of the model you are trying to load.

**Comment by MorenoLaQuatra** [comment]
Thank you for the quick response and the detailed guidance it clarified a lot!

I’m currently facing some challenges with setting up the environment for the model. Even when following the installation instructions, I’m running into compatibility issues when using CUDA version 12 or above. Could you confirm if there’s a known incompatibility with CUDA >= 12, or if there are specific steps I should take to resolve this?

Thanks again for your help!

**Comment by SiavashShams** [comment]
In our environment, we used PyTorch 2.2.2 with CUDA 11.8. Compatibility can depend on both your GPU's support for CUDA 12 and the specific PyTorch version you install. I don't see any reason for it to not work with CUDA 12.x as long as you install the correct torch version and your GPU is compatible. Please checkout [this](https://pytorch.org/get-started/previous-versions/) link for torch installation.

Hope this helps,

**Comment by MorenoLaQuatra** [comment]
It helped a lot, actually I was able to run it only with torch==2.1.1 for problems with vision mamba and mamba_ssm. However I think I sorted it out. Just wanted to confirm a few parameters:

```python
vim_config = {
    # Vision Mamba Arguments
    "patch_size": 16,
    "embed_dim": 768,
    "depth": 12,
    "rms_norm": True, 
    "residual_in_fp32": True, 
    "fused_add_norm": True, 
    "if_rope": False,
    "if_rope_residual": False, 
    "bimamba_type": "v2",
    "drop_path_rate": 0.1,
    "stride": 16,
    "channels": 1,
    "num_classes": 1000,
    "drop_rate": 0.0,
    "norm_epsilon": 1e-5,
    "if_bidirectional": True,
    "final_pool_type": "none",
    "if_abs_pos_embed": True, 
    "if_bimamba": True, 
    "if_cls_token": True, 
    "if_devide_out": False, 
    "use_double_cls_token": False, 
    "use_middle_cls_token": False,  
}

# Load SSAMBA Model
label_dim = 527
input_fdim = 128
input_tdim = 1024
fshape = 16
tshape = 16
fstride = 16
tstride = 16
```

Are they correct? I basically took all of them from the deafault config in the repo. I needed to change only `"if_cls_token": True`, `"if_abs_pos_embed": True`, that were set to false, because otherwise I had errors with `VisionMamba` missing some attributes.

**Comment by SiavashShams** [comment]
Yes, it is mostly correct. But if you are trying to use the 'base' size you should set the depth to 24, and embed_dim to 768. Please refer to the Table 1 in our paper to see the configurations of different sizes.

**Comment by MorenoLaQuatra** [comment]
![image](https://github.com/user-attachments/assets/eb9e9237-8755-4404-bda0-7bba97f3cbe5)

The depth is thus set to 24 for all models, right? Thanks for your help!
